обновила WorkoutReportTest

diff --git a/.github/workflows/gitActions.yml b/.github/workflows/gitActions.yml
--- a/.github/workflows/gitActions.yml
+++ b/.github/workflows/gitActions.yml
@@ -5,7 +5,6 @@
 # They are provided by a third-party and are governed by
 # separate terms of service, privacy policy, and support
 # documentation.
-
 name: FinalSurge CI
 
 on:
@@ -29,32 +28,36 @@ jobs:
           distribution: 'temurin'
           cache: maven
 
+
+      - name: Install Allure
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y allure
+
       - name: Run tests
         run: mvn clean test
         continue-on-error: true
 
-      - name: Get Allure history
-        uses: actions/checkout@v4
+
+      - name: Check allure-results
         if: always()
-        continue-on-error: true
-        with:
-          ref: gp-pagesnew
-          path: gp-pagesnew
+        run: |
+          ls -la target/allure-results || echo "allure-results not found"
 
-      - name: Allure Report action from marketplace
-        uses: simple-elf/allure-report-action@master
+
+      - name: Generate Allure report
         if: always()
-        with:
-          allure_results: target/allure-results
-          allure_history: allure-history
+        run: |
+          allure generate target/allure-results --clean -o allure-report
 
-
-      - name: Upload Allure report as artifact
+     
+      - name: Upload Allure report
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: allure-report
-          path: allure-history
+          path: allure-report
+
 
       - name: Deploy report to Github Pages
         if: always()
@@ -62,4 +65,6 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gp-pagesnew
-          publish_dir: allure-history
+          publish_dir: allure-report
+          force_orphan: false
+          keep_files: true
